# Definir a plataforma global e a versão do iOS
workspace 'Jokes'
platform :ios, '16.4'

target 'jokes' do
  # Usar frameworks dinâmicos
  use_frameworks!
  project 'jokes.project'

  # Pods para o projeto jokes
  pod 'SnapKit'
  pod 'CoreAPI', :path => 'Libs/CoreAPI'
  pod 'JokeGenerator', :path => 'Libs/JokeGenerator'

  target 'jokesTests' do
    inherit! :search_paths
  end

  target 'jokesUITests' do
    inherit! :search_paths
  end

end

target 'CoreAPI' do
  project '/Users/joaovictor/Documents/Mentoria/jokes/Libs/CoreAPI/CoreAPI.xcodeproj'
  pod 'CoreAPI', :path => 'Libs/CoreAPI'
end

target 'CoreAPIInterface' do
  project '/Users/joaovictor/Documents/Mentoria/jokes/Libs/CoreAPIInterface/CoreAPIInterface.xcodeproj'
  pod 'CoreAPIInterface', :path => 'Libs/CoreAPIInterface'
end

target 'JokeGenerator' do
  project '/Users/joaovictor/Documents/Mentoria/jokes/Libs/JokeGenerator/JokeGenerator.xcodeproj'
  pod 'JokeGenerator', :path => 'Libs/JokeGenerator'
  pod 'SnapKit'

  target 'JokeGeneratorTests' do
    inherit! :search_paths
  end

end

target 'JokeGeneratorInterface' do
  project '/Users/joaovictor/Documents/Mentoria/jokes/Libs/JokeGeneratorInterface/JokeGeneratorInterface.xcodeproj'
  pod 'JokeGeneratorInterface', :path => 'Libs/JokeGeneratorInterface'
end