# Definir a plataforma global e a versão do iOS
workspace 'Jokes'
platform :ios, '16.4'

target 'jokes' do
  # Usar frameworks dinâmicos
  use_frameworks!
  project 'jokes.project'

  # Pods para o projeto jokes
  pod 'SnapKit'

  target 'jokesTests' do
    inherit! :search_paths
  end

  target 'jokesUITests' do
    inherit! :search_paths
  end

end